### ISSUE TITLE
golint - package name contains underscores

### ISSUE THREAD

**Issue by scottjbarr** [IftekherSunny/go_country#1]
Running `golint .` on this project gives a number of warnings, including warnings on package name containing an underscore.

Maybe run `golint .` and see what you think?

**Comment by IftekherSunny** [comment]
got it. It'll be better if I'll use package name gocountry instead of go_country???

@scottjbarr I need suggestion about the package name.

**Comment by scottjbarr** [comment]
Maybe just `country` (this would stutter) or `countries`?

**Comment by IftekherSunny** [comment]
@scottjbarr done. now package name is country. And fixes all ```golint .``` warnings.


thanks @scottjbarr for your feedback. Don't forget to give star mark 👍
